### ISSUE TITLE
Add compatibility with 9.21

### ISSUE THREAD

**Issue by seletskiy** [kovetskiy/urxvt-fifo#2]
See example at https://github.com/muennich/urxvt-perls/commit/10c64a552fad22de0b6e7f1f8da81b445e7abc70

**Comment by kovetskiy** [comment]
10$

**Comment by seletskiy** [comment]
:dollar: :dollar: :dollar: :dollar: :dollar: :dollar: :dollar: :dollar: :dollar: :dollar: 

Works on 9.22 without changes.
